Initial support for generating ASP.NET Core Controllers
claasd/caffoa.net pull request #24
Opened 2023-09-06 10:10 UTC by kleferbe

Generating ASP.NET Core controllers is a bit different in that the generated controller files become user code and will be carefully updated with new methods found in the API by caffoa, without changing or removing existing methods.

This way we can keep the advantages of all the binding magic of asp.net core and modify the method signatures and attributes as needed.

2023-09-06 13:02 UTC, claasd commented
There is a lot of edge cases that are not yet working correctly.
Please add a Demo Project in demo/ folder (DemoAsp), and add generation for the controller to the caffoa.yml
```
  - apiPath: tests/base.openapi.yml
    config:
      prefix: Asp
      flavor: SystemTextJson
    model:
      namespace: DemoAsp.Model.Base
      targetFolder: ./demo/DemoAsp/Model/Base

  - apiPath: tests/openapi.yml
    config:
      prefix: Asp
      flavor: SystemTextJson
      imports:
        - DemoAsp.Model.Base
    model:
      namespace: DemoAsp.Model
      targetFolder: ./demo/DemoAsp/Model
    controller:
      targetFolder: demo/DemoAsp
      namespace: DemoAsp
      name: DemoAsp
```

You will find a lot of issues with includes and object naming.

2023-09-06 13:07 UTC, claasd requested changes

2023-09-06 13:07 UTC, claasd commented on CdIts.Caffoa.Cli/Generator/ModelGenerator.cs
> +            };
```suggestion
            {
                CaffoaConfig.GenerationFlavor.SystemTextJson => "JsonStringEnumConverter",
                _ => "StringEnumConverter",
             };
```

2023-09-06 13:07 UTC, claasd commented on CdIts.Caffoa.Cli/Generator/ModelGenerator.cs
> +            };
the default is null if nothing is given,

2023-09-06 13:07 UTC, claasd commented on CdIts.Caffoa.Cli/Generator/ModelGenerator.cs
> +            };
... and default null means Json.NET

2023-09-08 10:25 UTC, claasd commented
Looks good so far, could you write some key points into the readme? Or should be start with experimental mode?

2023-09-08 10:26 UTC, claasd approved these changes

2023-09-12 08:43 UTC, kleferbe commented
Most things should now be working and whats not is mostly System,Text.Json model related.
Added a demo project for ASP.NET with Newtonsoft too.

2023-09-19 06:55 UTC, claasd approved these changes

2023-09-19 06:55 UTC, merged